### ISSUE TITLE
The cdn used is bad

### ISSUE THREAD

**Issue by LeedaCode** [englercj/playground#19]
Hello,I am an Asian user using pixi playground.
We have noticed that the cloudfront used by pixi plaryground performs poorly in China. Opening a 282kb pixi.js file takes about 31 seconds to load, which caused a lot of trouble for our development. Thank you so much for the pixi playground, so great product, thank you for designing him, he is great!
                                                                                                                               Thank！
![image](https://user-images.githubusercontent.com/34672750/77053434-4dc18700-6a09-11ea-97a8-8e01e751b630.png)

**Comment by englercj** [comment]
I don't use CloudFront (from AWS) because it doesn't work in China at all. I use Cloudflare has a fast China version but it costs money, a lot of money.

I'm not sure what alternatives I have to making this run well in that region, if someone from the area is willing to help out I'd really appreciate it.

**Comment by LeedaCode** [comment]
Oh! Indeed it will cost a lot of money. So why not host the file on github?

**Comment by englercj** [comment]
Github isn't a CDN :)

Also I don't host the pixi.js file, pixi does. They do host it on CloudFront. I tried to get the conversation of switching hosts moving along but didn't get the traction necessary to finish: https://github.com/pixijs/pixi.js/pull/5862
