### ISSUE TITLE
custom timeout refresh plz

### ISSUE THREAD

**Issue by djmisterjon** [englercj/playground#6]
we need a custom timeout refresh please :)
it's a pain, the refreshment is too fast in some cases.
![image](https://user-images.githubusercontent.com/24865815/59382481-d5b48b00-8d2b-11e9-8cad-eea63641f615.png)

**Comment by englercj** [comment]
What do you mean by too fast? What is the problem you are trying to solve?

**Comment by djmisterjon** [comment]
the issue happen on big project.
the update are too fast i think.
for small projet it fine, but on big example , i get many freeze when i write a simple letter.
The update take ~1,2 seconde for each letters.

**Comment by englercj** [comment]
Oh i see what you're saying the refresh is painful for a large playground, and because it happens so often you are having a poor editing experience.

I think I would want to have a "manual update" checkbox for that when checked gives you a button to click when you want it to update.

Also profiling the update to see if there is something we can do to make it faster would be good.

**Comment by djmisterjon** [comment]
yes a check box for disable the live update it a good idea.

**Comment by englercj** [comment]
Fixed by 4ef92956793fe67810b3821a6829b1a2aef41ce6.

There is now a manual Refresh button and a checkbox in the settings to disable auto update.
